---
# =============================================================================
# Payment Service
# =============================================================================

apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: korczewski-services
  labels:
    app: payment
    app.kubernetes.io/name: payment
    app.kubernetes.io/component: payment
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: payment
