---
# =============================================================================
# Shop Service
# =============================================================================

apiVersion: v1
kind: Service
metadata:
  name: shop
  namespace: korczewski-services
  labels:
    app: shop
    app.kubernetes.io/name: shop
    app.kubernetes.io/component: shop
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: shop
