# =============================================================================
# L2P Backend Kustomization
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: l2p-backend

namespace: korczewski-services

labels:
  - pairs:
      app.kubernetes.io/part-of: korczewski
      app.kubernetes.io/component: backend
      tier: services

resources:
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
