---
# =============================================================================
# Payment Service IngressRoute
# =============================================================================

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: payment
  namespace: korczewski-services
  labels:
    app: payment
    app.kubernetes.io/name: payment
    app.kubernetes.io/component: payment
spec:
  routes:
    - match: Host(`shop.korczewski.de`) || Host(`payment.korczewski.de`)
      kind: Rule
      services:
        - name: payment
          port: 3000
      middlewares:
        - name: user-auth-chain
          namespace: korczewski-infra
  tls: {}
