---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-storage
provisioner: smb.csi.k8s.io
parameters:
  source: "//10.10.0.3/SMB-Share"
  # if only subdirectory is used, use:
  # subDir: "k8s-data"
  csi.storage.k8s.io/provisioner-secret-name: "smbcreds"
  csi.storage.k8s.io/provisioner-secret-namespace: "korczewski-infra"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "korczewski-infra"
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0700
  - file_mode=0600
  - uid=999
  - gid=999
  - noperm
  - mfsymlinks
  - cache=none
  - noserverino
