apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault
  namespace: korczewski-infra
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`dashboard.korczewski.de`) || Host(`vault.korczewski.de`)
      kind: Rule
      services:
        - name: vault-ui
          port: 8200
  tls:
    secretName: korczewski-tls
