# =============================================================================
# Traefik Kustomization
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: traefik

namespace: korczewski-infra

labels:
  - pairs:
      app.kubernetes.io/part-of: korczewski
      app.kubernetes.io/component: ingress-controller
      tier: infrastructure

resources:
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - middlewares.yaml
  - tlsstore.yaml
  - ingressroute-dashboard.yaml
