apiVersion: v1
kind: Service
metadata:
  name: shared-postgres
  namespace: korczewski-services
spec:
  type: ExternalName
  externalName: postgres.korczewski-infra.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: shared-postgres
  namespace: korczewski-infra
spec:
  type: ExternalName
  externalName: postgres.korczewski-infra.svc.cluster.local
