apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: videovault-credentials
  namespace: korczewski-services
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: videovault-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: videovault
